* forvol

forvol is a package that contains various methods used to calculate the volume 
of trees using equations implemented by the Forest Inventory and Analysis program 
under the United States Forest Service. The main objective of this project is to
provide a free and open source high level package in R for interacting with and testing the performance
of taper, biomass and volume equations, while functioning as a suitable equation
library to be used by other programs (such as forest inventory compilers and
merchandisers).

forvol is in a **pre-release** development stage, with only base functionality
and a few volume equations. Please use at your own discretion.

** Installation

Although we are not currently on CRAN, using devtools, forvol can be installed thusly

#+begin_src
library(devtools)
install_git("https://github.com/brycefrank/forvol.git")
#+end_src

** Current Status
   
   forvol currently only supports select CVTS equations, mostly for species in the Pacific
   Northwest (for a complete list, see [[https://github.com/brycefrank/forvol/wiki/Supported-Equations:-CVTS][Supported Equations - CVTS]])
   with plans to expand to merchantable volume, taper, and biomass equations.

   If there is an equation or feature you would like to see implemented, please submit an
   [[https://github.com/brycefrank/forvol/issues][issue]] to this repository or send an email (address listed below). 
   
** Collaboration
   
   Be it submission of issues (above) or help in development, testing, and documentation,
   there are many opportunities for collaboration. This project is in its early phase,
   so the opportunity is ripe to guide the structure of forvol to make it a succesful
   equation resource. Please send an email if you are interested in collaborating.

** Contact

   bryce.frank@oregonstate.edu

