A place for todos and logs and such.

* General Todo list
**** TODO Instead of using csv's and parsing, save all csv's as .rds
**** TODO Create species lookup function, good for debugging
**** TODO Refactor and decide on consistent variable names
     - Species Number, Species Code??
     - Region String, Location String??
     - etc
**** TODO Try to resolve the 'no_visible binding...' errors
**** TODO Create a dataframe of region ID's and descriptions (global)
**** TODO Create a dataframe of species codes and descriptions (global)
* Log
** <2017-12-13 Wed> 
   :LOGBOOK:
   CLOCK: [2017-12-13 Wed 10:12]--[2017-12-13 Wed 16:03] =>  5:51
   :END:
*** Working on Tests                                                  :tests:
    - Converted [[file:'test/cvts_test.xslx'][cvts_test.xlsx]] to a .rds format
      - Not without some trouble, apparently .rds (along with saveRDS and readRDS) is the proper format 
    - Wrote test_cvts function in [[file:test/test.R][test.R]], a test on Douglas-fir was encouraging, but not perfect,
      the average difference was 0.03 cubic feet. My guess is some sort of a rounding error is
      involved on one of the coefficients, but the performance is good enough for now.
*** Merchantable Equations                                         :merchvol:
    - Time to start working on equations .csv. I want to flesh out Douglas-fir first, just to get
      a feel on how this softwood boardfoot volume equations work.
    - Deciding to put this off for now, I need to think of how to handle the structure
*** Adding more CVTS equations                                         :cvts:
    - Added CU263004 (WH), CU000077(WRC), fairly straightforward
    - Ran into some conceptual issues with CU122011, where there is a diameter break in how
      the equation is calculated at 6 inches dbh. It may be best to have the BuildEquation() function
      be defined by location, species **and** diameter. Feeling pretty good about the structure
      implemented in file:test/cvts_equations.csv (I renamed this file to be more explicit in what
      it provides, should allow for easier extensibility later on if taper, etc is added)
*** Expanding file:R/config.R and file:R/eq.R
    - I need to make sure the change in file name is reflected in these scripts, and I have been wanting
      to implement some error handling
    - Added some functions to ease debugging and development (FindCSV and GetEquationString)
    - I then tested WH volumes (passed) and RC (no CVTS data for RC)
** <2017-12-14 Thu> 
   :LOGBOOK:
   CLOCK: [2017-12-14 Thu 08:05]--[2017-12-14 Thu 17:00]
   :END:
   - Generally, today I want to work on testing, documentation, and fixing style
*** Automated Testing for CVTS                                        :tests:
    - Got at least partway done with the config test, checks for missing equations
*** Ponderosa pine equation (i.e. MacLean & Berger)                    :cvts:
    - Wrote into file:bin/pipo.R as just an R function to get started, probably the best
      course of action is to implement just the > 6 inch piece into the equation csv first
      and then see how that works
    - Also, the Western Oregon CVTS volumes do not seem to line up with the coefficients provided
      by the file:excel/volcfgrs_eqn_coefs.xlsx, but the volumes for California Mixed Conifer do
      line up...so it may be worthwhile to check the other coefficients and heed the testing
      results.
** <2017-12-15 Fri>  
   :LOGBOOK:
   CLOCK: [2017-12-15 Fri 08:11]--[2017-12-15 Fri 14:00]
   :END:
   - The main goal today is to switch the equations .csv over to functions
     and develop higher level functions for interacting w/library
     - calc_vol()
*** csv functions
    - Had some trouble parsing the function strings with populated betas,
      had to convert back into a string and re-parse and evaluate. There
      are probably cleaner ways to do this, but this at least preserves the
      readability of the equation strings.
    - One possibility is to keep just the function "body" instead of the
      'function' tag...but could just be equally messy...
    - I like this approach for now, and it would not be hard to convert the
      function strings into actual functions if that is the route we choose to
      go
*** Higher level functions                                    :documentation:
    - Going to start by making a prototype in Jupyter notebooks, should tranlsate
      well into a sample later on
** <2017-12-16 Sat> 
*** File Structure
    - Deleted some directories and moved a few things around
*** Bug Fix
    - Was not searching for coefficients by the correct column,
      fixed (hopefully)
*** Docstrings                                                :documentation:
    - Adding some doc strings to file:R/config.R and file:R/eq.R
    - Tested docstring generation w/Roxygen2, seemed straightforward
*** Test Visualization                                                :tests:
    - It would be nice for users to see what equations have been completed,
      along with their performance. One idea is to create an n by n raster
      plot (using ggplot perhaps) for each volume type where the X axis represents
      the region ('OR_W', 'OR_E'...etc) and the Y axis represents the species.
      The raster cell would then indicate in some way the performance of the equation,
      whether or not it exists, was tested, etc etc. This would make a nice to-do list
      for me and be translucent for the user reading documentation.
** <2017-12-17 Sun> 
   - A lot of other stuff to do today, so we'll see what gets done, best bet is to
     finish the visualization idea from yesterday
* Equations Checklist
  - Mark done only if written and tested
*** Could be automated fully  
** Western Oregon
*** CVTS [4/7] 
    - [X] 202 - Douglas-fir
    - [ ] 242 - Western Redcedar
    - [X] 260 - Western Hemlock
    - [X] 122 -Ponderosa Pine
    - [X] Lodgepole Pine
    - [X] Red Alder
    - [ ] etc.
*** CV4 [0/7] 
    - [ ] 202 - Douglas-fir
    - [ ] 242 - Western Redcedar
    - [ ] 260 - Western Hemlock
    - [ ] Ponderosa Pine
    - [ ] Lodgepole Pine
    - [ ] Red Alder
    - [ ] etc.
*** SV632 [ ]
* Archive
**** DONE Match computed volumes ('krishna.xlsx') to forvol volumes
     CLOSED: [2017-12-13 Wed 16:11]
      - Part of a larger task to create automated testing script
        moving to archive
***** First for 'W_OR' then for all records
      file:csv/all_eqs.csv
      file:R/config.R
**** DONE Create automated testing script for CVTS
     CLOSED: [2017-12-16 Sat 09:29]
     - Should go through every species in each configuration csv and check the
       testing data. Best to limit to Western Oregon due to the 
     - Moved to archive, not done but underway
**** DONE Investigate volume discrepancies for DF CVTS equations
     CLOSED: [2017-12-16 Sat 09:30]
